services:
  github-runner:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        RUNNER_VERSION: "2.329.0"
    restart: unless-stopped
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GITHUB_REPOSITORY=${GITHUB_REPOSITORY}
      - RUNNER_PREFIX=${RUNNER_PREFIX:-}
      # Pass the host workspace path so workflows can mount it in spawned containers
      # This resolves ./workspaces to an absolute path at runtime
      - HOST_WORKSPACE_ROOT=${PWD}/workspaces
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # Mount host workspace so both runner and spawned containers can access it
      - ./workspaces:/home/runner/_work
    deploy:
      replicas: 5
